#!/usr/bin/env bash

# Set Nginx to run as nginx user
sed -i 's/user .*/user nginx;/g' /etc/nginx/nginx.conf

# Modify Nginx server block to listen on all active IPs on port 8080
sed -i 's/^.*listen .*$/\tlisten 8080;/g' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
service nginx restart
